### ISSUE TITLE
Please link to upstream project from README

### ISSUE THREAD

**Issue by charles-dyfis-net** [R0GGER/mistserver#7]
Google is sometimes finding this Dockerfile when folks are trying to reach https://github.com/DDVTECH/mistserver

It would be helpful to have a prominent link.

**Comment by R0GGER** [comment]
The README.md contains several references to  the creators of the software, https://mistserver.org.

**Comment by charles-dyfis-net** [comment]
Right -- the request is to link to _their github repository_ directly, since it's searches for "mistserver github" and the like that are ending up here.
